## System of equations-1:

In [13]:
import numpy as np
#Defining the equation in matrix form:
#Defining the co-effient matrix:
A_1=np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
#Defining the vector containing the constant terms
b_1=np.array([1, 0, 4])
#Solution:
x_1=np.linalg.solve(A_1,b_1)
print("The solution of the system of equations-1 is \n",x_1)

The solution of the system of equations-1 is 
 [ 0.03508772 -0.23684211  0.65789474]


## System of equations-2:

In [14]:
#Defining the equation in matrix form:
#Defining the co-effient matrix:
A_2=np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
#Defining the vector containing the constant terms
b_2=np.array([9, 7, 6])
#Solution:
x_2=np.linalg.solve(A_2,b_2)
print("The solution of the system of equations-2 is \n",x_2)

The solution of the system of equations-2 is 
 [0.99578947 0.95789474 0.79157895]


## System of equations-3:

In [15]:
#Defining the equation in matrix form:
#Defining the co-effient matrix:
A_3=np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8, -1], [0, 0, -1, 5]])
#Defining the vector containing the constant terms
b_3=np.array([6, 25, -11, -11])
#Solution:
x_3=np.linalg.solve(A_3,b_3)
print("The solution of the system of equations-3 is \n",x_3)

The solution of the system of equations-3 is 
 [-0.79764706  2.79529412 -0.25882353 -2.25176471]


## System of equations-4:

In [16]:
#Defining the equation in matrix form:
#Defining the co-effient matrix:
A_4=np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5, -1, -1], [-1, -1, -1, 
  4, 0], [0, 2, -1, 1, 4]])
#Defining the vector containing the constant terms
b_4=np.array([6, 6, 6, 6, 6])
#Solution:
x_4=np.linalg.solve(A_4,b_4)
print("The solution of the system of equations-4 is \n",x_4)

The solution of the system of equations-4 is 
 [ 0.78663239 -1.00257069  1.86632391  1.9125964   1.98971722]
