## Importing modules

In [31]:
import time
import numpy as np

## Defining the matrices

In [32]:
matrix1 = [[2,1],[1,0]]
matrix2 = [[2,1],[1,0],[0,1]]
matrix3 = [[2,1],[-1,1],[1,1],[2,-1]]
matrix4 = [[1,1,0],[-1,0,1],[0,1,-1],[1,1,-1]]
matrix5 = [[0,1,1],[0,1,0],[1,1,0],[0,1,0],[1,0,1]]

#Defining an array of the matrices
matrices = [matrix1, matrix2, matrix3, matrix4, matrix5]
decomposed_matrices = []

## To decompose the matrices and record the time

In [33]:
for i in range(5):
    decomposed = []
    start_time = time.time_ns()
    decomp = np.linalg.svd(matrices[i])
    print("Time taken for decomposition of matrix ", i+1, " is = ", time.time_ns() - start_time, " nano seconds.")
    for j in range(3):
        decomposed.append(decomp[j])
    decomposed_matrices.append(decomp)
    print("The decomposed matrices of matrix ", i+1, " are \n -->", decomp[0],"\n -->", decomp[1]," and \n -->", decomp[2])
    print("\n \n")

Time taken for decomposition of matrix  1  is =  182367  nano seconds.
The decomposed matrices of matrix  1  are 
 --> [[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]] 
 --> [2.41421356 0.41421356]  and 
 --> [[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]

 

Time taken for decomposition of matrix  2  is =  116091  nano seconds.
The decomposed matrices of matrix  2  are 
 --> [[-9.12870929e-01  4.80183453e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]] 
 --> [2.44948974 1.        ]  and 
 --> [[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]

 

Time taken for decomposition of matrix  3  is =  104791  nano seconds.
The decomposed matrices of matrix  3  are 
 --> [[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]] 
 --> [3.16227766 2.        ]

## Verification

In [34]:
singular_values = []
for idx in range(len(decomposed_matrices)):
    s = np.zeros((len(matrices[idx]), len(matrices[idx][0])))

    for d in range(len(decomposed_matrices[idx][1])):
        s[d][d] = decomposed_matrices[idx][1][d]
    result=np.dot(np.dot(decomposed_matrices[idx][0], s), decomposed_matrices[idx][2])
    print("Multiplication gives us ", result)
print("We can clearly see the decomposition is correct.")

Multiplication gives us  [[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -3.81016887e-17]]
Multiplication gives us  [[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -6.81060746e-17]
 [-1.23617226e-16  1.00000000e+00]]
Multiplication gives us  [[ 2.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 2. -1.]]
Multiplication gives us  [[ 1.00000000e+00  1.00000000e+00  2.01436552e-17]
 [-1.00000000e+00  2.32001774e-16  1.00000000e+00]
 [-2.21127337e-16  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]]
Multiplication gives us  [[-1.92849653e-16  1.00000000e+00  1.00000000e+00]
 [ 1.07252213e-16  1.00000000e+00 -2.29557465e-16]
 [ 1.00000000e+00  1.00000000e+00 -7.38436957e-16]
 [ 9.89586488e-17  1.00000000e+00 -2.21263901e-16]
 [ 1.00000000e+00 -6.00744882e-16  1.00000000e+00]]
We can clearly see the decomposition is correct.
